export const offers = [
    {
        _id: 1,
        category: "camping",
        title: "Experience an island night at a variety of resorts",
        img: "https://i.ibb.co/YNW1xRC/camping.webp",
        desc: "No visit is complete without an ‘Island Night’ cultural show for an unforgettable experience. Available at a variety of resorts and cultural centres on Rarotonga, Aitutaki and Atiu, they are a wonderful evening where passionate locals share our history and traditions through music, song, dance and food. Highly entertaining and fun for everyone, especially when the crowd participates in our traditional dance moves. A highlight for visitors are the exhilarating performances at cultural villages like Te Vara Nui and Highland Paradise Culture Centre or by local dance teams during the island nights staged around Rarotonga by the resorts and hotels. Delicious buffet meals featuring favourite local dishes like ika mata (marinated raw fish salad) are included in the island night packages. There are also the island nights where an umu kai is featured. This buffet style feast of food cooked in a traditional earth oven or umu is a wonderful experience.",
        price: 180,
        addedBy: "Iftikhar",
    },
    {
        _id: 2,
        category: "guide",
        title: "Visit a cultural village and learn about history.",
        img: "https://i.ibb.co/dMdMwC7/guide.webp",
        desc: "Ancient ways of tribal life can be experienced at one of our authentic village tours on Rarotonga or Aitutaki. On the same soil our ancestors lived and died, learn about our tribal customs and rich history of tribal warfare, invasion and cannibalism before the arrival of Christianity. Examine historical artifacts such as farming tools, weapons and traditional dress. As well as cooking techniques, weaving is demonstrated for everything from making huts and bags with kikau to clothing, hats, mats and fans from both pandanus and rito. For those who would rather paddle a kayak instead, there are single and double kayaks available too. Their boards are also equipped with colourful lights on the bottom, making them perfect for nighttime paddling. ",
        price: 180,
        addedBy: "Iftikhar",
    },
    {
        _id: 3,
        category: "beaches",
        title: "Special Deals And Last Minute Amazing Offers",
        img: "https://i.ibb.co/xGd1DqW/beaches.webp",
        desc: "Perfect for the vast turquoise playground of the Cook Islands, paddle boarding and the lagoon go together like bikinis and sunshine. A great way to cruise and explore, there’s so much to see. Travelling at 4km and hour, sea scooters are a really fun and easy way to explore the incredible undersea creatures that call the shores of Rarotonga home. Explore the live coral reef all around the island by snorkelling right off the beach. Perfect conditions offer both impressive visibility and warm water all year round. Beautiful beaches and safe, clear lagoons makes stand up paddle boarding the perfect way to enjoy a day on the water. The Lagoon Explorer Stand Up Paddle Board & Snorkel Tour lasts for approximately 2 hours.",
        price: 130,
        addedBy: "Iftikhar",
    },
    {
        _id: 4,
        category: "rides",
        title: "So many ways to explore incredibly clear beach",
        img: "https://i.ibb.co/ZBjd52h/rides.webp",
        desc: "Stunning views in the Cook Islands continue below the crystal clear waters where marine life is abundant, colourful and diverse in the lagoon. Explore the live coral reef all around the island by snorkelling right off the beach, joining a sea scooter tour or jumping on a SUP. Perfect conditions offer both impressive visibility and warm water all year round. Explore the live coral reef all around the island by snorkelling right off the beach. Perfect conditions offer both impressive visibility and warm water all year round. Ask your hotel or a local for directions to these spots as well as other snorkelling sites. If you are looking for snorkelling in Aitutaki try one of the many lagoon cruise tours available.",
        price: 110,
        addedBy: "Iftikhar",
    },
    {
        _id: 5,
        category: "popular",
        title: "Choose The Destination Just Right For Your Vacation",
        img: "https://i.ibb.co/zHVDykZ/popular.webp",
        desc: "Sea Scooters are a fun and easy way to see more of Rarotonga's underwater world. Each sea scooter is lightweight and equipped with a three level speed button meaning drivers are in control of their experience and can go at their own pace. Before going on tour, KiteSUP and Ariki Adventures will conduct a short sea scooter test in shallow water to ensure everyone is comfortable using the device. Along with using a sea scooter to cruise Rarotonga's waters, tour goers will also use a snorkel, mask and fins. With hundreds of tropical fish species and 73 types of live coral, the diversity of marine life in Rarotonga won't disappoint. There's so much to explore and with a sea scooter snorkellers can cover more ground.",
        price: 150,
        addedBy: "Iftikhar",
    },
    {
        _id: 6,
        category: "budget",
        title: "Special Deals And Last Minute Amazing Offers",
        img: "https://i.ibb.co/j6MfsDs/budget.webp",
        desc: "Perfect for the vast turquoise playground of the Cook Islands, paddle boarding and the lagoon go together like bikinis and sunshine. A great way to cruise and explore, there’s so much to see. Stand up paddling is a great way to spot giant trevally, vibrant blue parrot fish, eagle rays, turtles and everything in between. Whether joining a downwind tour of the lagoon, using it as a blissed-out sunbathing lounger or a diving platform for the kids, there are many options for hiring paddle boards on the beach, from cafés or hotels. Your accommodation provider may even have these included with your stay! There are several guided SUP tours in Muri, Rarotonga that provide a memorable experience.",
        price: 180,
        addedBy: "Iftikhar",
    },
]
